up

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,18 +1,16 @@
 #! /bin/sh
 
+if [ $(id -u) -ne 0 ]; then
+    echo "Super privilege required"
+    echo "e.g. sudo $0"
+    exit 1
+fi
 
-ROOT="$(cd "$(dirname "$0")" && pwd)"
-cd "$ROOT"
+_ROOT="$(pwd)" && cd "$(dirname "$0")" && ROOT="$(pwd)"
 
 VIMVERSION="$(vim --version|head -n1|awk '{print $5}'|sed 's/\.//')"
 if [ -z "$VIMVERSION" ]; then
     echo "err: vim not installed"
-    exit 1
-fi
-
-if [ $(id -u) -ne 0 ]; then
-    echo "Superuser previlege required"
-    echo "e.g. sudo $0"
     exit 1
 fi
 
